[package]
name = "cliff3-rust-util"
version = "0.1.0"
edition = "2021"
authors = ["JoonHo Son <joonho.son@me.com>"]

[features]
string  = []
default = ["string"]

[dependencies]
lazy_static = "1.4.0"
regex = "1.10.0"
